
name: Build LectorTickets APK

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Preparar uv
        uses: astral-sh/setup-uv@v6

      - name: Verificar Flet
        run: uv run flet --version --json

      - name: Compilar APK
        run: uv run flet build apk --yes --verbose --build-number ${{ github.run_number }}

      - name: Publicar APK
        uses: actions/upload-artifact@v7
        with:
          name: LectorTickets-APK
          path: build/apk/
          if-no-files-found: error
